<a href="https://colab.research.google.com/github/kinghim17/ANN-regression/blob/main/Copy_of_Artificial_Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.15.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [3]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [5]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into the Training set and Test set

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Part 2 - Building the ANN

### Initializing the ANN

In [7]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [8]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [9]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [10]:
ann.add(tf.keras.layers.Dense(units=1))

## Part 3 - Training the ANN

### Compiling the ANN

In [11]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

### Training the ANN model on the Training set

In [12]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
240/240 [==============================] - 2s 4ms/step - loss: 252660.3281
Epoch 2/100
240/240 [==============================] - 1s 4ms/step - loss: 50182.6289
Epoch 3/100
240/240 [==============================] - 1s 3ms/step - loss: 418.1886
Epoch 4/100
240/240 [==============================] - 1s 2ms/step - loss: 275.1767
Epoch 5/100
240/240 [==============================] - 1s 2ms/step - loss: 269.1489
Epoch 6/100
240/240 [==============================] - 0s 2ms/step - loss: 262.3840
Epoch 7/100
240/240 [==============================] - 1s 2ms/step - loss: 254.8586
Epoch 8/100
240/240 [==============================] - 0s 2ms/step - loss: 246.2489
Epoch 9/100
240/240 [==============================] - 1s 2ms/step - loss: 236.9515
Epoch 10/100
240/240 [==============================] - 1s 2ms/step - loss: 226.3529
Epoch 11/100
240/240 [==============================] - 1s 2ms/step - loss: 215.2623
Epoch 12/100
240/240 [==============================] - 0s 2ms/step -

### Predicting the results of the Test set

In [13]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

60/60 [==============================] - 0s 1ms/step
[[429.29 431.23]
 [460.35 460.01]
 [463.83 461.14]
 ...
 [471.11 473.26]
 [437.88 438.  ]
 [457.12 463.28]]


### evaluation of the performance

In [14]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9027776349358867